-- 按顺序执行所有初始化脚本
-- psql -U postgres -d fuxi -f sql/00_init.sql

\i sql/01_extensions.sql
\i sql/02_notes.sql
\i sql/03_graph.sql
\i sql/04_wiki.sql
\i sql/05_history.sql
\i sql/06_jobs.sql
\i sql/07_chunks.sql
\i sql/08_auth.sql
\i sql/09_history_user.sql
\i sql/10_user_username.sql
\i sql/11_audit.sql
\i sql/12_account_security.sql
\i sql/13_tokens.sql
\i sql/14_notes_list.sql
\i sql/15_tags.sql
\i sql/16_generated_qa.sql
\i sql/17_jobs_qa_gen.sql
\i sql/18_spaces.sql
\i sql/19_mcp_tokens.sql
\i sql/20_notes_space.sql
\i sql/21_wiki_space.sql
\i sql/22_mcp_token_space.sql
\i sql/23_default_membership.sql
\i sql/24_space_hardening.sql
\i sql/25_m3_lifecycle.sql
\i sql/26_m3_governance.sql
\i sql/27_m3_jobs.sql
\i sql/28_m3_qa_trace.sql
\i sql/29_m4_connectors.sql
\i sql/30_m4_distribution.sql
\i sql/31_m4_feedback.sql
\i sql/32_m4_agent.sql
\i sql/33_m4_jobs.sql
\i sql/34_undelete_version.sql
